
name: 'dbt_snowflake_contoso_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_snowflake_contoso_demo'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# tell dbt to build all models in the directory
models:
  dbt_snowflake_contoso_demo:
      # Applies to all files under models/sources
      sources:
        salesforce:
          materialized: view

# Vars
vars:
    # Fivetran's Salesforce dbt package vars
    ## DB settings
    salesforce_database: JACKM_CONTOSO    
    salesforce_schema: SALESFORCE
    ## Model config
    salesforce__manager_performance: false
    salesforce__owner_performance: false
    salesforce__sales_snapshot: true
    salesforce__opportunity_enhanced: true
    salesforce__contact_enhanced: true
    salesforce__daily_activity: false
    salesforce__opportunity_line_item_enhanced: false
    salesforce__order_enabled: false