{{ config(materialized='table') }}

with source_data as (
    SELECT 
        A.NAME PROSPECT_NAME, 
        COUNT(O.ID) AS ACTIVE_OPPORTUNITIES, 
        SUM(O.AMOUNT) AS TOTAL_AMOUNT, 
        SUM(O.EXPECTED_REVENUE) TOTAL_EXPECTED_REVENUE,
        MAX(O.LAST_ACTIVITY_DATE) MOST_RECENT_ACTIVITY
    FROM "JACKM_CONTOSO"."SALESFORCE"."OPPORTUNITY" O
    LEFT JOIN "JACKM_CONTOSO"."SALESFORCE"."ACCOUNT" A 
        ON A.ID = O.ACCOUNT_ID
    WHERE NOT O.IS_CLOSED AND NOT O.IS_WON
    GROUP BY A.NAME
)

select *
from source_data