{{ config(materialized='table') }}

WITH sales_overview AS (
  SELECT 
      DATE_TRUNC(MONTH, FS.DATEKEY) AS MONTH,
      DC.CHANNELNAME AS CHANNEL_NAME,
      DS.STORENAME AS STORE_NAME,
      SUM((UNITPRICE * SALESQUANTITY)) AS GROSS_SALES,
      SUM((UNITPRICE * SALESQUANTITY) - DISCOUNTAMOUNT - RETURNAMOUNT) AS NET_SALES,
      SUM((UNITPRICE * SALESQUANTITY) - DISCOUNTAMOUNT - RETURNAMOUNT) - SUM(UNITCOST * SALESQUANTITY) AS GROSS_MARGIN,
      SUM(UNITCOST * SALESQUANTITY) AS COST_TOTAL,
      ROUND(SUM(UNITCOST * SALESQUANTITY) / SUM((UNITPRICE * SALESQUANTITY) - DISCOUNTAMOUNT - RETURNAMOUNT) * 100, 2) AS NET_SALES_COST_RATIO
  FROM "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."DIMSTORE" DS
  LEFT JOIN "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."FACTSALES" FS
      ON DS.STOREKEY = FS.STOREKEY
  LEFT JOIN "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."DIMCHANNEL" DC
      ON FS.CHANNELKEY = DC.CHANNELKEY
  GROUP BY 
      MONTH, 
      CHANNEL_NAME, 
      STORE_NAME
  ORDER BY GROSS_MARGIN DESC
) 

SELECT *
FROM sales_overview
