{{ config(materialized='table') }}

WITH FACT_STRATEGY_PLANNING AS (
  SELECT 
      FSP.DATEKEY,
      DA.ACCOUNTNAME,
      DS.SCENARIONAME,
      DPC.PRODUCTCATEGORYNAME,
      DE.ENTITYNAME,
      FSP.AMOUNT
  FROM "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."FACTSTRATEGYPLAN" FSP
  LEFT JOIN "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."DIMACCOUNT" DA
      ON FSP.ACCOUNTKEY = DA.ACCOUNTKEY
  LEFT JOIN "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."DIMSCENARIO" DS
      ON FSP.SCENARIOKEY = DS.SCENARIOKEY
  LEFT JOIN "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."DIMPRODUCTCATEGORY" DPC
      ON FSP.PRODUCTCATEGORYKEY = DPC.PRODUCTCATEGORYKEY
  LEFT JOIN "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."DIMENTITY" DE
      ON FSP.ENTITYKEY = DE.ENTITYKEY
)
SELECT *
FROM FACT_STRATEGY_PLANNING