{{ config(materialized='table') }}

WITH source AS (
    SELECT 
        G.REGIONCOUNTRYNAME AS COUNTRY,
        COUNT(1) NUM_CUSTOMERS,
        ROUND(AVG(DATEDIFF('year', C.BIRTHDATE, CURRENT_TIMESTAMP))) AS AVERAGE_AGE,
        ROUND(AVG(C.YEARLYINCOME), 3) AS AVERAGE_INCOME,
        ROUND(AVG(C.TOTALCHILDREN), 2) AS AVERAGE_NUM_CHILDREN,
        ROUND(AVG(DATEDIFF('year', BIRTHDATE, DATEFIRSTPURCHASE))) AS AVERAGE_AGE_AT_FIRST_PURCHASE
    FROM "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."DIMCUSTOMER" C
    LEFT JOIN "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."DIMGEOGRAPHY" G
        ON C.GEOGRAPHYKEY = G.GEOGRAPHYKEY
    GROUP BY G.REGIONCOUNTRYNAME
)

SELECT *
FROM source