{{ config(materialized='table') }}

WITH source AS (
    SELECT
        DATE_TRUNC(MONTH, SQ.DATEKEY) AS MONTH,
        SC.SCENARIONAME AS SCENARIO_NAME,
        SUM(SQ.SALESAMOUNTQUOTA) AS SCENARION_SALES_EMOUNT_QUOTA
    FROM "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."FACTSALESQUOTA" SQ
    LEFT JOIN "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."DIMSCENARIO" SC
        ON SQ.SCENARIOKEY = SC.SCENARIOKEY
    GROUP BY MONTH, SC.SCENARIONAME
    ORDER BY MONTH, SC.SCENARIONAME ASC
)

SELECT *
FROM source