WITH gross_margin_actual AS (
  SELECT
      DATE_TRUNC(MONTH, S.DATEKEY) AS MONTH,
      SUM(((UNITPRICE * SALESQUANTITY) - DISCOUNTAMOUNT) - ((UNITCOST * SALESQUANTITY) - RETURNAMOUNT)) AS TOTAL_ACTUAL_GROSS_MARGIN
  FROM "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."FACTSALES" S
  GROUP BY MONTH
), gross_margin_quota AS (
  SELECT
      DATE_TRUNC(MONTH, SQ.DATEKEY) AS MONTH,
      SUM(GROSSMARGINQUOTA) AS GROSS_MARGIN_QUOTA
  FROM "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."FACTSALESQUOTA" SQ
  GROUP BY MONTH
)
SELECT 
    GMA.MONTH,
    GMA.TOTAL_ACTUAL_GROSS_MARGIN,
    GMQ.GROSS_MARGIN_QUOTA
FROM gross_margin_actual GMA
LEFT JOIN gross_margin_quota GMQ
    ON GMA.MONTH = GMQ.MONTH
ORDER BY GMA.MONTH