{{ config(materialized='table') }}

WITH sales_actual AS (
  SELECT
      DATE_TRUNC(MONTH, S.DATEKEY) AS MONTH,
      SUM((UNITPRICE * SALESQUANTITY) - DISCOUNTAMOUNT) AS SALES_ACTUAL_TOTAL
  FROM "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."FACTSALES" S
  GROUP BY MONTH
), sales_quota AS (
  SELECT
      DATE_TRUNC(MONTH, SQ.DATEKEY) AS MONTH,
      SUM(SALESAMOUNTQUOTA) AS SALES_TOTAL_QUOTA
  FROM "JACKM_CONTOSO"."CONTOSO_RETAIL_DW_DBO"."FACTSALESQUOTA" SQ
  GROUP BY MONTH
)
SELECT 
    SA.MONTH,
    SA.SALES_ACTUAL_TOTAL,
    SQ.SALES_TOTAL_QUOTA
FROM sales_actual SA
LEFT JOIN sales_quota SQ
    ON SA.MONTH = SQ.MONTH
ORDER BY SA.MONTH