
version: 2

models:
    - name: salesforce_opportunity_quick_overview
      description: "Basic transform for Salesforce"
      columns:
          - name: PROSPECT_ACCOUNT_ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: salesforce_opportunity_quick_view
      description: "Basic view for Salesforce"
