version: 2
    
sources:
  - name: salesforce
    schema: salesforce
    database: jackm_contoso
    loader: fivetran
    loaded_at_field: _fivetran_synced
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: Account 
        identifier: account
        loaded_at_field: _fivetran_synced
      - name: Opportunity 
        identifier: opportunity
        loaded_at_field: _fivetran_synced

